### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by KeKl** [Frassle/ciltk#3]
Hi,

can you please also add the needed dependencies for weaving in the nuget package?
FSharp.Core.dll
...

That would be great!

**Comment by Frassle** [comment]
Should be fixed by https://github.com/Frassle/ciltk/commit/d3d093d1180f7842a4e0826d80c9074312c1cad0 and https://github.com/Frassle/ciltk/commit/7afb0df88ffac422b499475e70ee7ed58c01cf4e
