### ISSUE TITLE
Not working with roslyn

### ISSUE THREAD

**Issue by KeKl** [Frassle/ciltk#4]
Hi,

I get an exception when I run the rewriter under visual Studio 2015.
I think this is an roslyn issue. Did you already tested this?

Regards

**Comment by Frassle** [comment]
I haven't tested with VS2015. If you post the exception I might be able to make a guess at whats causing it.

**Comment by KeKl** [comment]
I took your opentk fork. Tested it under VS2013. Rewriting was ok.

In VS2015 the build run successfully. But rewritung exists with an exception:


>CilTK Rewriter
>Reading assembly from .\opentk-silk\Binaries\OpenTK\Debug\OpenTK.dll
>Writing assembly to .\opentk-silk\Binaries\OpenTK\Debug\OpenTK.dll

>Unbehandelte Ausnahme: Microsoft.Cci.Pdb.PdbDebugException: Unknown custom metadata item >kind: 6
>   bei Microsoft.Cci.Pdb.PdbFunction.ReadCustomMetadata(BitAccess bits)
>   bei Microsoft.Cci.Pdb.PdbFunction..ctor(ManProcSym proc, BitAccess bits)
>   bei Microsoft.Cci.Pdb.PdbFunction.LoadManagedFunctions(BitAccess bits, UInt32 limit, Boolean >readStrings)
>   bei Microsoft.Cci.Pdb.PdbFile.LoadFuncsFromDbiModule(BitAccess bits, DbiModuleInfo info, >IntHashTable names, ArrayLis
>t funcList, Boolean readStrings, MsfDirectory dir, Dictionary`2 nameIndex, PdbReader reader)
>   bei Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, Dictionary`2& >tokenToSourceMapping, String& sourceServerData
>)
>   bei Mono.Cecil.Pdb.PdbReader.PopulateFunctions()
   bei Mono.Cecil.Pdb.PdbReader.ProcessDebugHeader(ImageDebugDirectory directory, Byte[] header)
   bei Mono.Cecil.ModuleDefinition.ProcessDebugHeader()
   bei Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   bei Mono.Cecil.ModuleReader.CreateModuleFrom(Image image, ReaderParameters parameters)
   bei Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   bei Mono.Cecil.AssemblyDefinition.ReadAssembly(String fileName, ReaderParameters parameters)
   bei Weave.Program.Main(String[] args) in d:\ciltk\Rewriter\Program.cs:Zeile 75.

**Comment by Frassle** [comment]
I think this is because of https://github.com/jbevain/cecil/issues/211. I'll update cecil to the 9.6 and that should fix this.

**Comment by Frassle** [comment]
Should be fixed by https://github.com/Frassle/ciltk/commit/488d5e82d0fb7c6e6a3028403928965095716f36
